---
# tasks file for user

- name: Ensure group "{{ user_primary_group }}" exists with GID = "{{ user_primaru_group_id }}"
  become: yes
  group:
    name: '{{ user_primary_group }}'
    state: present
    gid: '{{ user_primaru_group_id }}'
   
- name: Adding user to the system 
  become: yes
  user:
    name: '{{ user_name }}'
    comment: John Doe
    uid: '{{ user_id }}'
    group: "{{ user_primary_group }}"
    password: '{{ user_password }}'
  changed_when: no

- name: Granting sudoers privileges and disable tty
  become: yes
  template:
    src: user-add.j2
    dest: /etc/sudoers.d/{{ user_name }}
    validate: '/usr/sbin/visudo -cf %s'

- name: Test on if user in group root
  shell: |
      time 5; sudo id
  become_user: '{{ user_name }}'
  become: yes
  register: user_data
  failed_when: user_data.stdout.split(" ")[0] != "uid=0(root)" 
  changed_when: no 
    
- name: Set authorized key took from file
  become: yes
  authorized_key:
    user: '{{ user_name }}'
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ lookup('env', 'HOME') + '/.ssh/*.pub' }}"
