---
- hosts: all

  tasks:
  - name: Provision Centos
    block:
      - setup: 
      - yum:
          name: "{{ item }}"
          state: installed
        with_items:
          - epel-release 
          - sudo 
    when: ansible_distribution == 'CentOS'

       
  
